# Generated by Django 2.0.3 on 2018-04-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pref_day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
                ('competitive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_players', models.IntegerField(default='2')),
                ('description', models.CharField(default='No description provided.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Api_Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('comp_json', models.CharField(max_length=15)),
                ('cas_json', models.CharField(max_length=15)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='No description provided.', max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_server', models.CharField(choices=[('usw', 'US-West'), ('use', 'US-East'), ('eu', 'Europe'), ('oce', 'Oceania'), ('as', 'Asia'), ('sam', 'South America'), ('saf', 'South Africa'), ('me', 'Middle-East')], default='usw', max_length=3)),
                ('birth_date', models.DateField(null=True)),
                ('sessions_played', models.IntegerField(default='0')),
                ('teamwork_commends', models.IntegerField(default='0')),
                ('communication_commends', models.IntegerField(default='0')),
                ('skill_commends', models.IntegerField(default='0')),
                ('positivity_commends', models.IntegerField(default='0')),
                ('discord_name', models.CharField(blank=True, max_length=37, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Connected_Game_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_player_tag', models.CharField(default='<Missing>', max_length=50)),
                ('platform', models.CharField(choices=[('ps4', 'Playstation 4'), ('xone', 'Xbox One'), ('pc', 'PC')], default='pc', max_length=5)),
                ('cas_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('comp_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('toxic', 'Toxicity'), ('sportsmanship', 'Unsportsmanlike Behaviour')], default='toxic', max_length=15)),
                ('datetime_sent', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_by_report', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game_Role')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Session')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Session'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reported_report', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile'),
        ),
    ]
