# Generated by Django 2.0.2 on 2018-03-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_server', models.CharField(choices=[('usw', 'US-West'), ('use', 'US-East'), ('eu', 'Europe'), ('oce', 'Oceania'), ('as', 'Asia'), ('sam', 'South America'), ('saf', 'South Africa'), ('me', 'Middle-East')], default='usw', max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sessions_played', models.IntegerField()),
                ('teamwork_commends', models.IntegerField()),
                ('communication_commends', models.IntegerField()),
                ('skill_commends', models.IntegerField()),
                ('positivity_commends', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
