# Generated by Django 2.0.2 on 2018-03-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pref_day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_players', models.IntegerField(default='2')),
                ('description', models.CharField(default='No description provided.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='No description provided.', max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('toxic', 'Toxicity'), ('sportsmanship', 'Unsportsmanlike Behaviour')], default='toxic', max_length=15)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_commenced', models.DateTimeField()),
                ('time_completed', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game_Role')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='communication_commends',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positivity_commends',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sessions_played',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill_commends',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teamwork_commends',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='session_profile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='session_profile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Session'),
        ),
        migrations.AddField(
            model_name='report',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_by_report', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Session'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reported_report', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile'),
        ),
    ]
