# Generated by Django 2.0.2 on 2018-03-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180320_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_role',
            old_name='name',
            new_name='role_name',
        ),
        migrations.AlterField(
            model_name='report',
            name='sent_by',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, related_name='sent_by_report', to='api.Profile'),
        ),
    ]
