# Generated by Django 2.0.2 on 2018-03-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180321_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_commenced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
