# Generated by Django 2.0.2 on 2018-03-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180321_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='time_created',
            new_name='datetime_created',
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
