# Generated by Django 2.0.2 on 2018-03-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180321_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='time_sent',
            new_name='datetime_sent',
        ),
    ]
