# Generated by Django 2.0.2 on 2018-03-23 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180321_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Api_Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('comp_json', models.CharField(max_length=15)),
                ('cas_json', models.CharField(max_length=15)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Connected_Game_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_player_name', models.CharField(default='<Missing>', max_length=50)),
                ('cas_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('comp_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('game_api', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game_Api_Connection')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='competitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_name',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile_connected_game_account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile'),
        ),
    ]
