# Generated by Django 2.0.3 on 2018-04-04 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Availability')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game')),
                ('game_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game_Role')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='profile_connected_game_account',
            name='game_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Game'),
        ),
    ]
