# Generated by Django 2.0.3 on 2018-04-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180404_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_preference',
            name='availability',
        ),
        migrations.AddField(
            model_name='user_preference',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='pref_days',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
